<a href="https://colab.research.google.com/github/Subhash-K45/python/blob/main/Linear%20Programming/Simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from scipy.optimize import linprog

# Objective function coefficients (maximization problem)
c = [-40, -30]

# Coefficients for the inequality constraints (Ax <= b)
A = np.array([[1, 1], [2, 1]])
b = np.array([12, 16])  # Corrected the order of constraints

# Bounds for variables
x0_bounds = (0, None)  # x1 >= 0
x1_bounds = (0, None)  # x2 >= 0

# Solve the linear programming problem
res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds], method='simplex')

# Extract the results
x1, x2 = res.x
z = -res.fun  # The 'fun' attribute returns the negative of the objective value

# Print the results
print("The matrix reads:")
print(f"x1 = {x1:.0f}")
print(f"x2 = {x2:.0f}")
print(f"z = {z:.0f}")


The matrix reads:
x1 = 4
x2 = 8
z = 400


<ipython-input-6-9dd00968d018>:16: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds], method='simplex')


In [38]:
import numpy as np

# Define the initial tableau (you need to convert the problem to standard form)
tableau = np.array([
    [1.0, 1.0, 1.0, 0.0, 12.0],
    [2.0, 1.0, 0.0, 1.0, 16.0],
    [40.0, 30.0, 0.0, 0.0, 0.0]
], dtype=float)

iteration = 0

while True:
    print(f"Iteration {iteration}:")
    print("Tableau:")
    print(tableau)

    # Check if the tableau is optimal
    if np.all(tableau[-1, :-1] <= 0):
        break

    # Select the entering variable (pivot column)
    pivot_col = np.where(tableau[-1, :-1] > 0)[0][0]

    # Compute the ratios for the leaving variable (pivot row)
    ratios = tableau[:-1, -1] / tableau[:-1, pivot_col]

    # Check for infeasibility
    if np.all(ratios <= 0):
        print("The problem is infeasible.")
        break

    pivot_row = np.argmin(ratios)

    # Pivot the tableau
    pivot_element = tableau[pivot_row, pivot_col]
    tableau[pivot_row, :] /= pivot_element

    for i in range(tableau.shape[0]):
        if i != pivot_row:
            multiplier = tableau[i, pivot_col]
            tableau[i, :] -= multiplier * tableau[pivot_row, :]

    iteration += 1

print("Final tableau:")
print(tableau)

# Extract the results
x1 = tableau[0, -1]
x2 = tableau[1, -1]
z = -tableau[-1, -1]

print("Final results:")
print(f"x1 = {x1:.4f}")
print(f"x2 = {x2:.4f}")
print(f"z = {z:.4f}")


Iteration 0:
Tableau:
[[ 1.  1.  1.  0. 12.]
 [ 2.  1.  0.  1. 16.]
 [40. 30.  0.  0.  0.]]
Iteration 1:
Tableau:
[[   0.     0.5    1.    -0.5    4. ]
 [   1.     0.5    0.     0.5    8. ]
 [   0.    10.     0.   -20.  -320. ]]
Iteration 2:
Tableau:
[[   0.    1.    2.   -1.    8.]
 [   1.    0.   -1.    1.    4.]
 [   0.    0.  -20.  -10. -400.]]
Final tableau:
[[   0.    1.    2.   -1.    8.]
 [   1.    0.   -1.    1.    4.]
 [   0.    0.  -20.  -10. -400.]]
Final results:
x1 = 8.0000
x2 = 4.0000
z = 400.0000


In [40]:
import numpy as np

# Define the initial tableau (you need to convert the problem to standard form)
tableau = np.array([
    [1.0, 1.0, 1.0, 0.0, 12.0],
    [2.0, 1.0, 0.0, 1.0, 16.0],
    [40.0, 30.0, 0.0, 0.0, 0.0]
], dtype=float)

iteration = 0

while True:
    print(f"Iteration {iteration}:")
    print("Tableau:")

    # Print the column labels
    print("   ", end="")
    for col in range(tableau.shape[1] - 1):
        print(f"x{col + 1}  ", end="")
    print("xb")

    # Print the tableau
    for row in range(tableau.shape[0]):
        print(f"x{row + 1} ", end="")
        for col in range(tableau.shape[1]):
            print(f"{tableau[row, col]:.2f} ", end="")
        print()

    # Check if the tableau is optimal
    if np.all(tableau[-1, :-1] <= 0):
        break

    # Select the entering variable (pivot column)
    pivot_col = np.where(tableau[-1, :-1] > 0)[0][0]

    # Compute the ratios for the leaving variable (pivot row)
    ratios = tableau[:-1, -1] / tableau[:-1, pivot_col]

    # Check for infeasibility
    if np.all(ratios <= 0):
        print("The problem is infeasible.")
        break

    pivot_row = np.argmin(ratios)

    # Pivot the tableau
    pivot_element = tableau[pivot_row, pivot_col]
    tableau[pivot_row, :] /= pivot_element

    for i in range(tableau.shape[0]):
        if i != pivot_row:
            multiplier = tableau[i, pivot_col]
            tableau[i, :] -= multiplier * tableau[pivot_row, :]

    iteration += 1

print("Final tableau:")
print("   ", end="")
for col in range(tableau.shape[1] - 1):
    print(f"x{col + 1}  ", end="")
print("xb")

# Print the final tableau
for row in range(tableau.shape[0]):
    print(f"x{row + 1} ", end="")
    for col in range(tableau.shape[1]):
        print(f"{tableau[row, col]:.2f} ", end="")
    print()

# Extract the results
x1 = tableau[0, -1]
x2 = tableau[1, -1]
z = -tableau[-1, -1]

print("Final results:")
print(f"x1 = {x1:.2f}")
print(f"x2 = {x2:.2f}")
print(f"z = {z:.2f}")


Iteration 0:
Tableau:
   x1  x2  x3  x4  xb
x1 1.00 1.00 1.00 0.00 12.00 
x2 2.00 1.00 0.00 1.00 16.00 
x3 40.00 30.00 0.00 0.00 0.00 
Iteration 1:
Tableau:
   x1  x2  x3  x4  xb
x1 0.00 0.50 1.00 -0.50 4.00 
x2 1.00 0.50 0.00 0.50 8.00 
x3 0.00 10.00 0.00 -20.00 -320.00 
Iteration 2:
Tableau:
   x1  x2  x3  x4  xb
x1 0.00 1.00 2.00 -1.00 8.00 
x2 1.00 0.00 -1.00 1.00 4.00 
x3 0.00 0.00 -20.00 -10.00 -400.00 
Final tableau:
   x1  x2  x3  x4  xb
x1 0.00 1.00 2.00 -1.00 8.00 
x2 1.00 0.00 -1.00 1.00 4.00 
x3 0.00 0.00 -20.00 -10.00 -400.00 
Final results:
x1 = 8.00
x2 = 4.00
z = 400.00
